import os
import logging
from git import Repo
from github import Github

# Configure logger
logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger(__name__)

def write_description_to_file(description, file_path):
    with open(file_path, 'w') as f:
        f.write(description)
    logger.debug(f"Written to {file_path}")

def create_and_push_branch(repo_dir, branch_name, file_path, commit_msg, description):
    repo = Repo(repo_dir)
    origin = repo.remote(name='origin')

    # Branch checkout or create
    if branch_name in repo.heads:
        logger.debug(f"Checking out existing branch: {branch_name}")
        repo.heads[branch_name].checkout()
    else:
        logger.debug(f"Creating and checking out new branch: {branch_name}")
        repo.git.checkout('HEAD', b=branch_name)

    # Update feature branch with latest main to avoid conflicts
    logger.debug("Fetching origin and merging origin/main")
    origin.fetch()
    repo.git.merge('origin/main')

    # Write updated description
    write_description_to_file(description, file_path)

    logger.debug(f"Adding file {file_path} to git")
    repo.git.add(file_path)
    logger.debug(f"Committing changes with message: {commit_msg}")
    repo.index.commit(commit_msg)

    # Push branch
    logger.debug(f"Pushing branch {branch_name} to origin")
    origin.push(branch_name)
    logger.debug(f"Pushed {branch_name}")

def create_pull_request(repo_name, branch_name, pr_title, pr_body, github_token):
    g = Github(github_token)
    repo = g.get_repo(repo_name)
    
    # Check for existing open PR from this branch
    logger.debug(f"Checking for existing open PRs from branch: {branch_name}")
    prs = repo.get_pulls(state='open', head=branch_name)
    for pr in prs:
        if pr.head.ref == branch_name:
            logger.debug(f"Existing PR found: {pr.html_url}")
            return pr.html_url
    
    # If no existing PR, create new one
    logger.debug(f"Creating new PR: {pr_title}")
    pr = repo.create_pull(title=pr_title, body=pr_body, head=branch_name, base='main')
    logger.debug(f"Created PR: {pr.html_url}")
    return pr.html_url

def automate_github_pr(description, repo_dir, repo_name, github_token):
    file_path = os.path.join(repo_dir, 'configs/downstream_table_description.md')
    branch_name = 'update-downstream-table-desc'
    commit_msg = 'Auto-update downstream table metadata description'
    pr_title = 'Update downstream table metadata description'
    pr_body = 'This PR updates the description for the downstream table generated by automation.'

    logger.debug("Starting automation for GitHub PR")
    create_and_push_branch(repo_dir, branch_name, file_path, commit_msg, description)
    pr_url = create_pull_request(repo_name, branch_name, pr_title, pr_body, github_token)
    logger.debug(f"Automation complete, PR URL: {pr_url}")
    return pr_url
