import os
import requests
import json
from databricks.sdk import WorkspaceClient
import logging

logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger(__name__)

class MetadataFramework:
    def __init__(self, host, databricks_token, model_serving_token=None, model_endpoint=None):
        logger.info("Initializing MetadataFramework")
        self.db_client = WorkspaceClient(host=host, token=databricks_token)
        self.model_endpoint = model_endpoint
        self.model_serving_token = model_serving_token
        logger.debug(f"Model endpoint: {model_endpoint}")

    def fetch_table_metadata(self, table_name):
        logger.debug(f"Fetching metadata for table: {table_name}")
        try:
            table_metadata = self.db_client.tables.get(full_name=table_name)
            logger.debug(f"Successfully fetched metadata for {table_name}")
            return table_metadata
        except Exception as e:
            logger.error(f"Error fetching metadata for {table_name}: {e}")
            raise

    def generate_description_and_pr_metadata(self, upstream_tables, downstream_table, sql_query):
        logger.info("Starting description and PR metadata generation")
        
        def format_table_info(table):
            columns = ', '.join(col.name for col in table.columns)
            return (
                f"Table Name   : {table.name}\n"
                f"Description  : {table.comment or 'No description'}\n"
                f"Columns      : {columns}\n"
            )

        upstream_info = "\n".join(format_table_info(table) for table in upstream_tables)
        downstream_cols = ', '.join(col.name for col in downstream_table.columns)

        logger.debug("Upstream Tables Info:\n%s", upstream_info)
        logger.debug("Downstream Table Info:\n%s", downstream_cols)

        prompt = (
            "Based on the following upstream tables and SQL transformation, generate a JSON response with:\n"
            "1. A clear description for the downstream table\n"
            "2. PR metadata (title, body, commit message)\n\n"
            "UPSTREAM TABLES:\n"
            f"{upstream_info}\n"
            "SQL TRANSFORMATION:\n"
            f"{sql_query}\n"
            "DOWNSTREAM TABLE SCHEMA:\n"
            f"Table Name   : {downstream_table.name}\n"
            f"Columns      : {downstream_cols}\n\n"
            "Please return a JSON response in this exact format:\n"
            "{\n"
            '  "description": "A concise 2-3 sentence description explaining what this table contains, how it\'s derived, and its business purpose",\n'
            '  "pr_metadata": {\n'
            '    "title": "Descriptive PR title",\n'
            '    "body": "Detailed PR body explaining the changes",\n'
            '    "commit_message": "Clear commit message describing the update"\n'
            '  }\n'
            "}\n\n"
            "Respond with valid JSON only:"
        )

        if not self.model_endpoint or not self.model_serving_token:
            logger.warning("Model endpoint or token is not provided, returning placeholder")
            return {
                "description": "This is a placeholder description generated for the downstream table based on upstream tables and SQL transformation.",
                "pr_metadata": {
                    "title": "Update downstream table metadata description",
                    "body": "This PR updates the description for the downstream table generated by automation.",
                    "commit_message": "Auto-update downstream table metadata description"
                }
            }

        headers = {
            "Authorization": f"Bearer {self.model_serving_token}",
            "Content-Type": "application/json"
        }

        payload = {
            "messages": [
                {
                    "role": "system",
                    "content": "You are a data engineer specializing in metadata descriptions. Always respond with valid JSON."
                },
                {
                    "role": "user",
                    "content": prompt
                }
            ],
            "max_tokens": 500,
            "temperature": 0.3
        }

        logger.debug("Sending request to model serving endpoint")
        try:
            response = requests.post(self.model_endpoint, headers=headers, json=payload)
            response.raise_for_status()
            result = response.json()
            logger.debug(f"Model response received: {result}")

            # Extract the text content from response
            content_parts = result['choices'][0]['message']['content']
            text_content = ""
            for part in content_parts:
                if part.get('type') == 'text' and 'text' in part:
                    text_content = part['text']
                    break

            if not text_content:
                logger.warning("No text content found in model response")
                text_content = str(result)

            logger.debug(f"Extracted text content: {text_content}")

            # Parse JSON from the model response
            try:
                parsed_result = json.loads(text_content.strip())
                logger.info("Successfully parsed JSON from model response")
                return parsed_result
            except json.JSONDecodeError as json_error:
                logger.error(f"Failed to parse JSON from model response: {json_error}")
                logger.debug(f"Raw text content: {text_content}")
                # Return fallback structure
                return {
                    "description": text_content.strip(),
                    "pr_metadata": {
                        "title": "Update downstream table metadata description",
                        "body": "This PR updates the description for the downstream table generated by automation.",
                        "commit_message": "Auto-update downstream table metadata description"
                    }
                }

        except Exception as e:
            logger.error(f"Error during model serving invocation: {e}")
            return {
                "description": "Failed to generate description due to model invocation error.",
                "pr_metadata": {
                    "title": "Update downstream table metadata description",
                    "body": "This PR updates the description for the downstream table generated by automation.",
                    "commit_message": "Auto-update downstream table metadata description"
                }
            }

    def run(self, upstream_table_names, downstream_table_name, sql_query):
        logger.info("Starting metadata framework run")
        try:
            upstream_tables = []
            for name in upstream_table_names:
                logger.debug(f"Fetching upstream table: {name}")
                upstream_tables.append(self.fetch_table_metadata(name))
            
            logger.debug(f"Fetching downstream table: {downstream_table_name}")
            downstream_table = self.fetch_table_metadata(downstream_table_name)
            
            result = self.generate_description_and_pr_metadata(upstream_tables, downstream_table, sql_query)
            logger.info("Metadata framework run completed successfully")
            return result
        except Exception as e:
            logger.error(f"Error in metadata framework run: {e}")
            raise
